### ISSUE TITLE
don't error out on cyclical objects

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/heroku-logger#10]
Since we try to flatten any objects in the logger, if they are cyclical it errors out. We need to cap the depth of objects being logged probably to something reasonable.

**Comment by damms005** [comment]
Or some other third party circular ref handler can be used, like https://github.com/kaelzhang/json-stringify

**Comment by ianstormtaylor** [comment]
Fixed in `0.3.1`.
