### ISSUE TITLE
Make flatten delimiter an option

### ISSUE THREAD

**Issue by loris** [ianstormtaylor/heroku-logger#11]
Hi,
you currently flatten deep objects (using https://github.com/hughsk/flat) setting the `#` delimiter instead of the `.` default.
Is there any reasoning behind that change? Do you think this is something that could be set back as an option in the constructor? (ie, `const logger = new Logger({ flatDelimiter: '.' });`)

**Comment by ianstormtaylor** [comment]
Hey @loris, I think I used `#` because I noticed that's what Heroku was using for the Postgres/Redis logging, and although I think `#` is weird, I wanted to follow them exactly.

But making it configurable sounds good to me. If you make a PR with an `options.delimiter` I'm down to merge! Thanks!

**Comment by loris** [comment]
Sure! here it is: https://github.com/ianstormtaylor/heroku-logger/pull/12
Thanks a lot
